---
- name: Change port Tomcat 8080 to 8501
  hosts: Endpoints
  become: true
  tasks:
    - name: Stop Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: stopped

    - name: Change Tomcat port to 8501
      ansible.builtin.replace:
        path: /opt/tomcat/conf/server.xml
        regexp: 'port="8080"'
        replace: 'port="8501"'

    - name: Start Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: started

    - name: Restart Tomcat service
      ansible.builtin.systemd:
        name: tomcat
        state: restarted

    - name: Check if Tomcat is running on port 8501
      ansible.builtin.command: "curl -s http://localhost:8501"
      register: tomcat_status

    - name: Ensure Tomcat is running
      ansible.builtin.debug:
        msg: "Tomcat is running on port 8501"
      when: "'Apache Tomcat' in tomcat_status.stdout"
